Repository aws/aws-rfdk, pull requests merged in 2020-11, with the labels that each got.

#201 chore: updates to the bump script
  bump.sh
Labels: contribution/core

#175 feat(deadline): versionquery construct
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/README.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/lib/service_tier.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/README.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/lib/service-tier.ts
  integ/components/deadline/deadline_01_repository/bin/deadline_01_repository.ts
  integ/components/deadline/deadline_02_renderQueue/bin/deadline_02_renderQueue.ts
  integ/components/deadline/deadline_03_workerFleet/bin/deadline_03_workerFleet.ts
  integ/lib/render-struct.ts
  integ/lib/storage-struct.ts
  packages/aws-rfdk/lib/core/lambdas/nodejs/lib/custom-resource/simple-resource.ts
  packages/aws-rfdk/lib/core/lambdas/nodejs/lib/version-provider/index.ts
  packages/aws-rfdk/lib/core/lambdas/nodejs/lib/version-provider/test/index-test.json
  packages/aws-rfdk/lib/core/lambdas/nodejs/lib/version-provider/test/version-provider.test.ts
  packages/aws-rfdk/lib/core/lambdas/nodejs/lib/version-provider/version-provider.ts
  packages/aws-rfdk/lib/core/lambdas/nodejs/lib/version-provider/version.ts
  packages/aws-rfdk/lib/core/lambdas/nodejs/version-provider/handler.ts
  packages/aws-rfdk/lib/core/lambdas/nodejs/version-provider/test/handler.test.ts
  packages/aws-rfdk/lib/core/lambdas/nodejs/version-provider/test/version.test.ts
  packages/aws-rfdk/lib/deadline/lib/index.ts
  packages/aws-rfdk/lib/deadline/lib/repository.ts
  packages/aws-rfdk/lib/deadline/lib/stage.ts
  packages/aws-rfdk/lib/deadline/lib/version-query.ts
  packages/aws-rfdk/lib/deadline/lib/version-ref.ts
  packages/aws-rfdk/lib/deadline/lib/version.ts
  packages/aws-rfdk/lib/deadline/test/asset-constants.ts
  packages/aws-rfdk/lib/deadline/test/render-queue.test.ts
  packages/aws-rfdk/lib/deadline/test/repository.test.ts
  packages/aws-rfdk/lib/deadline/test/stage.test.ts
  packages/aws-rfdk/lib/deadline/test/thinkbox-docker-recipes.test.ts
  packages/aws-rfdk/lib/deadline/test/usage-based-licensing.test.ts
  packages/aws-rfdk/lib/deadline/test/version-query.test.ts
  packages/aws-rfdk/lib/deadline/test/version.test.ts
  packages/aws-rfdk/lib/deadline/test/worker-fleet.test.ts
Labels: contribution/core

#209 feat(deadline): add WorkerInstanceConfiguration construct
  packages/aws-rfdk/lib/core/lib/script-assets.ts
  packages/aws-rfdk/lib/core/test/asset-constants.ts
  packages/aws-rfdk/lib/deadline/lib/index.ts
  packages/aws-rfdk/lib/deadline/lib/worker-configuration.ts
  packages/aws-rfdk/lib/deadline/lib/worker-fleet.ts
  packages/aws-rfdk/lib/deadline/scripts/bash/configureWorker.sh
  packages/aws-rfdk/lib/deadline/scripts/bash/configureWorkerHealthCheck.sh
  packages/aws-rfdk/lib/deadline/scripts/powershell/configureWorker.ps1
  packages/aws-rfdk/lib/deadline/scripts/powershell/configureWorkerHealthCheck.ps1
  packages/aws-rfdk/lib/deadline/test/asset-constants.ts
  packages/aws-rfdk/lib/deadline/test/worker-configuration.test.ts
  packages/aws-rfdk/lib/deadline/test/worker-fleet.test.ts
Labels: contribution/core, feature-request

#217 chore: configure dependabot to ignore cdk toolchain
  .github/dependabot.yml
Labels: contribution/core, dependencies

#216 chore: Adds supported Deadline versions to CHANGELOG
  bump.sh
  scripts/getSupportedDeadlineVersions.ts
Labels: contribution/core

#224 chore: pull amazonlinux Docker image from ECR
  scripts/prep_release.sh
  scripts/pull_amazonlinux_from_ecr.sh
Labels: contribution/core

#225 chore: fix to region detection during release
  scripts/prep_release.sh
Labels: bug, contribution/core

#210 feat(integ): add ability to run integration tests using ECR images
  integ/lib/ThinkboxDockerImageOverrides.ts
  integ/lib/render-struct.ts
  integ/package.json
  integ/test-config.sh
  packages/aws-rfdk/lib/deadline/lib/thinkbox-docker-recipes.ts
Labels: contribution/core

#231 chore(merge-back): 0.20.0
  CHANGELOG.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/package.json
  integ/package.json
  lambda-layers/package.json
  lambda-layers/yarn.lock
  lerna.json
  package.json
  packages/aws-rfdk/package.json
  tools/cdk-build-tools/package.json
  tools/pkglint/package.json
Labels: pr/no-squash

#214 chore: updates to all-in-aws ts example
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/README.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/bin/app.ts
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/bin/config.ts
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/lib/service-tier.ts
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/package.json
Labels: contribution/core

#233 chore: removed redundant packages field in lerna.json
  lerna.json
Labels: contribution/core

#180 feat(examples): Added examples for Spot Event Plugin Deployment
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/lib/storage_tier.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/lib/storage-tier.ts
  examples/deadline/All-In-AWS-Infrastructure-SEP/README.md
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/.gitignore
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/README.md
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/cdk.json
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/package/__init__.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/package/__init__.pyc
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/package/app.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/package/lib/__init__.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/package/lib/sep_stack.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/requirements.txt
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/source.bat
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/.gitignore
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/.npmignore
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/README.md
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/bin/app.ts
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/cdk.json
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/clean.sh
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/lib/sep-stack.ts
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/package.json
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/tsconfig.json
Labels: contribution/core

#205 chore(integ): configure tests to run in pipeline
  integ/.npmignore
  integ/components/deadline/common/scripts/bash/component_e2e.sh
  integ/components/deadline/common/scripts/bash/deploy-utils.sh
  integ/components/deadline/deadline_03_workerFleet/bin/deadline_03_workerFleet.ts
  integ/components/deadline/deadline_03_workerFleetHttp/bin/deadline_03_workerFleetHttp.ts
  integ/components/deadline/deadline_03_workerFleetHttp/cdk.json
  integ/components/deadline/deadline_03_workerFleetHttp/lib/workerFleetHttp-testing-tier.ts
  integ/components/deadline/deadline_03_workerFleetHttp/scripts/bastion/testing/WF-report-worker-sets.sh
  integ/components/deadline/deadline_03_workerFleetHttp/scripts/bastion/testing/WF-report-workers.sh
  integ/components/deadline/deadline_03_workerFleetHttp/scripts/bastion/testing/WF-submit-jobs-to-sets.sh
  integ/components/deadline/deadline_03_workerFleetHttp/test/deadline_03_workerFleetHttp.test.ts
  integ/components/deadline/deadline_04_workerFleetHttps/bin/deadline_04_workerFleetHttps.ts
  integ/components/deadline/deadline_04_workerFleetHttps/cdk.json
  integ/components/deadline/deadline_04_workerFleetHttps/lib/workerFleetHttps-testing-tier.ts
  integ/components/deadline/deadline_04_workerFleetHttps/scripts/bastion/testing/WFS-report-worker-sets.sh
  integ/components/deadline/deadline_04_workerFleetHttps/scripts/bastion/testing/WFS-report-workers.sh
  integ/components/deadline/deadline_04_workerFleetHttps/scripts/bastion/testing/WFS-submit-jobs-to-sets.sh
  integ/components/deadline/deadline_04_workerFleetHttps/test/deadline_04_workerFleetHttps.test.ts
  integ/lib/render-struct.ts
  integ/lib/testing-tier.ts
  integ/package.json
  integ/scripts/bash/cleanup.sh
  integ/scripts/bash/rfdk-integ-e2e.sh
  integ/scripts/bash/run-e2e-automated.sh
  integ/scripts/bash/stage-deadline.sh
  integ/scripts/bash/tear-down.sh
  integ/scripts/bash/teardown-infrastructure.sh
  integ/test-config.sh
  scripts/prep_release.sh
Labels: contribution/core

#160 feat(integ): use configurable version of Deadline for integration tests
  integ/scripts/bash/rfdk-integ-e2e.sh
  integ/scripts/bash/run-e2e-automated.sh
  integ/scripts/bash/set-test-variables.sh
  integ/scripts/bash/stage-deadline.sh
  integ/test-config.sh
Labels: contribution/core

#230 fix(deadline): lock down DocDC engine to version 3.6.0
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/lib/storage_tier.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/lib/storage-tier.ts
  integ/lib/storage-struct.ts
  packages/aws-rfdk/lib/deadline/lib/database-connection.ts
  packages/aws-rfdk/lib/deadline/lib/repository.ts
  packages/aws-rfdk/lib/deadline/test/database-connection.test.ts
Labels: contribution/core

#246 fix(deadline): Fix cyclic stack dependency when using UBL
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/app.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/lib/compute_tier.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/lib/service_tier.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/bin/app.ts
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/lib/compute-tier.ts
  packages/aws-rfdk/lib/deadline/lib/usage-based-licensing.ts
  packages/aws-rfdk/lib/deadline/test/usage-based-licensing.test.ts
Labels: contribution/core

#252 fix(deadline): bad file path for Repository when using VersionQuery
  packages/aws-rfdk/lib/deadline/lib/repository.ts
Labels: contribution/core

#242 feat(core): Add configurable expiry to X.509 certificates
  packages/aws-rfdk/lib/core/lib/x509-certificate.ts
  packages/aws-rfdk/lib/core/test/x509-certificate.test.ts
  packages/aws-rfdk/lib/lambdas/nodejs/lib/x509-certs/certificate.ts
  packages/aws-rfdk/lib/lambdas/nodejs/lib/x509-certs/test/certificate.test.ts
  packages/aws-rfdk/lib/lambdas/nodejs/x509-certificate/handlers.ts
  packages/aws-rfdk/lib/lambdas/nodejs/x509-certificate/types.ts
Labels: contribution/core

#254 chore(merge-back): 0.21.0
  CHANGELOG.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/package.json
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/package.json
  integ/package.json
  lambda-layers/package.json
  lambda-layers/yarn.lock
  lerna.json
  package.json
  packages/aws-rfdk/package.json
  tools/cdk-build-tools/package.json
  tools/pkglint/package.json
Labels: pr/no-squash
