Repository aws/aws-rfdk, pull requests merged in 2021-04, with the labels that each got.

#373 feat(examples): Demonstrate how to send an email alarm when EFS burst credits below a threshold
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/app.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/config.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/lib/storage_tier.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/bin/app.ts
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/bin/config.ts
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/lib/storage-tier.ts
  packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/filesystem-ops.ts
  packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/test/handlers.test.ts
Labels: contribution/core

#377 chore(deps): force netmask version to avoid cve-2021-28918
  package.json
  yarn.lock
Labels: contribution/core

#381 fix(examples): make alarm email optional and add README instructions
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/README.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/lib/storage_tier.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/README.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/lib/storage-tier.ts
Labels: contribution/core, documentation

#382 chore(release): 0.29.0
  CHANGELOG.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/README.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/app.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/config.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/lib/service_tier.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/lib/storage_tier.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/README.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/bin/app.ts
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/bin/config.ts
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/lib/service-tier.ts
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/lib/storage-tier.ts
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/package.json
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/package.json
  examples/deadline/EC2-Image-Builder/python/setup.py
  examples/deadline/EC2-Image-Builder/ts/package.json
  integ/lib/storage-struct.ts
  integ/package.json
  integ/scripts/bash/rfdk-integ-e2e.sh
  lambda-layers/package.json
  lambda-layers/yarn.lock
  lerna.json
  package.json
  packages/aws-rfdk/lib/core/lib/exporting-log-group.ts
  packages/aws-rfdk/lib/core/lib/health-monitor.ts
  packages/aws-rfdk/lib/core/lib/imported-acm-certificate.ts
  packages/aws-rfdk/lib/core/lib/index.ts
  packages/aws-rfdk/lib/core/lib/log-group-factory.ts
  packages/aws-rfdk/lib/core/lib/mongodb-instance.ts
  packages/aws-rfdk/lib/core/lib/mongodb-post-install.ts
  packages/aws-rfdk/lib/core/lib/mountable-ebs.ts
  packages/aws-rfdk/lib/core/lib/mountable-efs.ts
  packages/aws-rfdk/lib/core/lib/mountable-filesystem.ts
  packages/aws-rfdk/lib/core/lib/pad-efs-storage.ts
  packages/aws-rfdk/lib/core/lib/staticip-server.ts
  packages/aws-rfdk/lib/core/lib/x509-certificate.ts
  packages/aws-rfdk/lib/core/test/health-monitor.test.ts
  packages/aws-rfdk/lib/core/test/mongodb-instance.test.ts
  packages/aws-rfdk/lib/core/test/mountable-ebs.test.ts
  packages/aws-rfdk/lib/core/test/pad-efs-storage.test.ts
  packages/aws-rfdk/lib/deadline/lib/render-queue-ref.ts
  packages/aws-rfdk/lib/deadline/lib/render-queue.ts
  packages/aws-rfdk/lib/deadline/lib/repository.ts
  packages/aws-rfdk/lib/deadline/lib/usage-based-licensing.ts
  packages/aws-rfdk/lib/deadline/lib/worker-fleet.ts
  packages/aws-rfdk/lib/deadline/scripts/bash/enableCacheFilesd.sh
  packages/aws-rfdk/lib/deadline/test/database-connection.test.ts
  packages/aws-rfdk/lib/deadline/test/render-queue.test.ts
  packages/aws-rfdk/lib/deadline/test/repository.test.ts
  packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/filesystem-ops.ts
  packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/handlers.ts
  packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/index.ts
  packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/test/handlers.test.ts
  packages/aws-rfdk/package.json
  tools/cdk-build-tools/config/eslintrc.js
  tools/cdk-build-tools/package.json
  tools/pkglint/lib/rules.ts
  tools/pkglint/package.json
  yarn.lock
Labels: pr/no-squash

#389 test(integ): add test for RCS process owner
  integ/components/deadline/deadline_02_renderQueue/scripts/bastion/testing/RQ-query-rcs-user.sh
  integ/components/deadline/deadline_02_renderQueue/test/deadline_02_renderQueue.test.ts
Labels: contribution/core

#398 chore(deps): bumping cdk from 1.96.0 to 1.99.0
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/package.json
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/package.json
  examples/deadline/EC2-Image-Builder/python/setup.py
  examples/deadline/EC2-Image-Builder/ts/package.json
  integ/package.json
  package.json
  packages/aws-rfdk/package.json
  tools/cdk-build-tools/package.json
  tools/pkglint/package.json
  yarn.lock
Labels: contribution/core

#392 feat(core): add ability to resolve mount targets using EFS API
  packages/aws-rfdk/lib/core/lib/mountable-efs.ts
  packages/aws-rfdk/lib/core/scripts/bash/metadataUtilities.sh
  packages/aws-rfdk/lib/core/scripts/bash/mountEfs.sh
  packages/aws-rfdk/lib/core/test/asset-constants.ts
  packages/aws-rfdk/lib/core/test/mountable-efs.test.ts
  packages/aws-rfdk/lib/deadline/test/repository.test.ts
Labels: contribution/core

#400 chore(release): 0.30.0
  CHANGELOG.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/package.json
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/package.json
  examples/deadline/EC2-Image-Builder/python/setup.py
  examples/deadline/EC2-Image-Builder/ts/package.json
  integ/components/deadline/deadline_02_renderQueue/scripts/bastion/testing/RQ-query-rcs-user.sh
  integ/components/deadline/deadline_02_renderQueue/test/deadline_02_renderQueue.test.ts
  integ/package.json
  lambda-layers/package.json
  lerna.json
  package.json
  packages/aws-rfdk/lib/core/lib/mountable-efs.ts
  packages/aws-rfdk/lib/core/scripts/bash/metadataUtilities.sh
  packages/aws-rfdk/lib/core/scripts/bash/mountEfs.sh
  packages/aws-rfdk/lib/core/test/asset-constants.ts
  packages/aws-rfdk/lib/core/test/mountable-efs.test.ts
  packages/aws-rfdk/lib/deadline/lib/configure-spot-event-plugin.ts
  packages/aws-rfdk/lib/deadline/lib/render-queue.ts
  packages/aws-rfdk/lib/deadline/lib/repository.ts
  packages/aws-rfdk/lib/deadline/lib/usage-based-licensing.ts
  packages/aws-rfdk/lib/deadline/scripts/bash/installDeadlineRepository.sh
  packages/aws-rfdk/lib/deadline/test/repository.test.ts
  packages/aws-rfdk/lib/deadline/test/usage-based-licensing.test.ts
  packages/aws-rfdk/lib/lambdas/nodejs/configure-spot-event-plugin/handler.ts
  packages/aws-rfdk/lib/lambdas/nodejs/lib/aws-lambda/types.ts
  packages/aws-rfdk/lib/lambdas/nodejs/lib/custom-resource/simple-resource.ts
  packages/aws-rfdk/lib/lambdas/nodejs/lib/deadline-client/deadline-client.ts
  packages/aws-rfdk/lib/lambdas/nodejs/lib/deadline-client/test/deadline-client.test.ts
  packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/test/handlers.test.ts
  packages/aws-rfdk/package.json
  tools/cdk-build-tools/package.json
  tools/pkglint/package.json
  yarn.lock
Labels: pr/no-squash

#401 chore(merge-back): 0.30.0
  CHANGELOG.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/package.json
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/package.json
  examples/deadline/EC2-Image-Builder/python/setup.py
  examples/deadline/EC2-Image-Builder/ts/package.json
  integ/package.json
  lambda-layers/package.json
  lerna.json
  package.json
  packages/aws-rfdk/package.json
  tools/cdk-build-tools/package.json
  tools/pkglint/package.json
Labels: pr/no-squash
