Repository aws/aws-rfdk, pull requests merged in 2021-07, with the labels that each got.

#470 feat(deadline): create Deadline Groups and Pools on deploy for ConfigureSpotEventPlugin
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/README.md
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/README.md
  packages/aws-rfdk/lib/deadline/README.md
  packages/aws-rfdk/lib/deadline/lib/configure-spot-event-plugin.ts
  packages/aws-rfdk/lib/deadline/lib/spot-event-plugin-fleet.ts
  packages/aws-rfdk/lib/lambdas/nodejs/configure-spot-event-plugin/handler.ts
  packages/aws-rfdk/lib/lambdas/nodejs/configure-spot-event-plugin/test/handler.test.ts
  packages/aws-rfdk/lib/lambdas/nodejs/configure-spot-event-plugin/types.ts
  packages/aws-rfdk/lib/lambdas/nodejs/lib/configure-spot-event-plugin/spot-event-plugin-client.ts
  packages/aws-rfdk/lib/lambdas/nodejs/lib/configure-spot-event-plugin/test/spot-event-plugin-client.test.ts
Labels: contribution/core

#500 chore(deps): bumping cdk from 1.108.1 to 1.111.0
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/package.json
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/package.json
  examples/deadline/EC2-Image-Builder/python/setup.py
  examples/deadline/EC2-Image-Builder/ts/package.json
  examples/deadline/Local-Zone/python/setup.py
  examples/deadline/Local-Zone/ts/package.json
  integ/package.json
  lambda-layers/package.json
  package.json
  packages/aws-rfdk/package.json
  tools/cdk-build-tools/package.json
  tools/pkglint/package.json
  yarn.lock
Labels: contribution/core, dependencies

#504 chore(integ): improve logging when refreshing credentials
  integ/components/deadline/common/scripts/bash/deploy-utils.sh
  integ/scripts/bash/run-e2e-automated.sh
  integ/scripts/bash/tear-down.sh
  integ/scripts/bash/teardown-infrastructure.sh
Labels: contribution/core

#506 chore(merge-back): 0.36.0
  CHANGELOG.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/package.json
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/package.json
  examples/deadline/EC2-Image-Builder/python/setup.py
  examples/deadline/EC2-Image-Builder/ts/package.json
  examples/deadline/Local-Zone/python/setup.py
  examples/deadline/Local-Zone/ts/package.json
  integ/package.json
  lambda-layers/package.json
  lambda-layers/yarn.lock
  lerna.json
  package.json
  packages/aws-rfdk/package.json
  tools/cdk-build-tools/package.json
  tools/pkglint/package.json
Labels: pr/no-squash

#491 feat(deadline): use TLS between RenderQueue and clients by default
  integ/lib/render-struct.ts
  packages/aws-rfdk/docs/upgrade/index.md
  packages/aws-rfdk/docs/upgrade/upgrading-0.37.md
  packages/aws-rfdk/lib/deadline/lib/render-queue-ref.ts
  packages/aws-rfdk/lib/deadline/lib/render-queue.ts
  packages/aws-rfdk/lib/deadline/test/configure-spot-event-plugin.test.ts
  packages/aws-rfdk/lib/deadline/test/render-queue.test.ts
  packages/aws-rfdk/lib/deadline/test/spot-event-plugin-fleet.test.ts
  packages/aws-rfdk/lib/deadline/test/usage-based-licensing.test.ts
  packages/aws-rfdk/lib/deadline/test/worker-configuration.test.ts
  packages/aws-rfdk/lib/deadline/test/worker-fleet.test.ts
Labels: contribution/core

#461 feat(core): add FSx for Lustre integration
  package.json
  packages/aws-rfdk/lib/core/lib/index.ts
  packages/aws-rfdk/lib/core/lib/mountable-fsx-lustre.ts
  packages/aws-rfdk/lib/core/scripts/bash/installLustreClient.sh
  packages/aws-rfdk/lib/core/scripts/bash/mountFsxLustre.sh
  packages/aws-rfdk/lib/core/test/mountable-fsx-lustre.test.ts
  packages/aws-rfdk/lib/deadline/lib/render-queue.ts
  packages/aws-rfdk/lib/deadline/lib/repository.ts
  packages/aws-rfdk/lib/deadline/scripts/bash/installDeadlineRepository.sh
  packages/aws-rfdk/lib/deadline/test/render-queue.test.ts
  packages/aws-rfdk/lib/deadline/test/repository.test.ts
  packages/aws-rfdk/package.json
  yarn.lock
Labels: contribution/core
