Repository aws/aws-rfdk, pull requests merged in 2021-11, with the labels that each got.

#626 fix(deadline): change dependency when configuring repository clients …
  packages/aws-rfdk/lib/deadline/lib/repository.ts
Labels: bug, contribution/core

#630 chore(docs): link to 0.38.0 upgrade docs in changelog
  CHANGELOG.md
Labels: documentation, breaking-change

#633 fix(deadline): configure identity registration settings using RenderQueue backend security group
  packages/aws-rfdk/lib/core/lib/deployment-instance.ts
  packages/aws-rfdk/lib/core/test/deployment-instance.test.ts
  packages/aws-rfdk/lib/deadline/lib/render-queue.ts
  packages/aws-rfdk/lib/deadline/lib/secrets-management.ts
  packages/aws-rfdk/lib/deadline/scripts/python/configure_identity_registration_settings.py
  packages/aws-rfdk/lib/deadline/scripts/python/test/test_configure_identity_registration_settings.py
  packages/aws-rfdk/lib/deadline/test/render-queue.test.ts
  packages/aws-rfdk/lib/deadline/test/secrets-management.test.ts
Labels: bug, contribution/core

#636 chore(release): 0.39.0
  .github/workflows/ci.yml
  CHANGELOG.md
  CONTRIBUTING.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/package.json
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/package.json
  examples/deadline/EC2-Image-Builder/python/setup.py
  examples/deadline/EC2-Image-Builder/ts/package.json
  examples/deadline/Local-Zone/python/setup.py
  examples/deadline/Local-Zone/ts/package.json
  integ/package.json
  lambda-layers/package.json
  lerna.json
  package.json
  packages/aws-rfdk/lib/core/lib/deployment-instance.ts
  packages/aws-rfdk/lib/core/test/deployment-instance.test.ts
  packages/aws-rfdk/lib/deadline/README.md
  packages/aws-rfdk/lib/deadline/lib/render-queue.ts
  packages/aws-rfdk/lib/deadline/lib/repository.ts
  packages/aws-rfdk/lib/deadline/lib/secrets-management.ts
  packages/aws-rfdk/lib/deadline/scripts/python/configure_identity_registration_settings.py
  packages/aws-rfdk/lib/deadline/scripts/python/test/test_configure_identity_registration_settings.py
  packages/aws-rfdk/lib/deadline/test/render-queue.test.ts
  packages/aws-rfdk/lib/deadline/test/secrets-management.test.ts
  packages/aws-rfdk/lib/lambdas/nodejs/lib/x509-certs/test/certificate.test.ts
  packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/filesystem-ops.ts
  packages/aws-rfdk/lib/lambdas/nodejs/pad-efs-storage/test/handlers.test.ts
  packages/aws-rfdk/package.json
  scripts/rfdk_build_environment.sh
  tools/cdk-build-tools/package.json
  tools/pkglint/package.json
Labels: pr/no-squash

#637 chore(merge-back): 0.39.0
  CHANGELOG.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/package.json
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/package.json
  examples/deadline/EC2-Image-Builder/python/setup.py
  examples/deadline/EC2-Image-Builder/ts/package.json
  examples/deadline/Local-Zone/python/setup.py
  examples/deadline/Local-Zone/ts/package.json
  integ/package.json
  lambda-layers/package.json
  lerna.json
  package.json
  packages/aws-rfdk/package.json
  tools/cdk-build-tools/package.json
  tools/pkglint/package.json
Labels: pr/no-squash

#513 feat(deadline): change SEP construct to use launch templates instead of launch specifications
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/package/app.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/package/config.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/package/lib/sep_stack.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/bin/app.ts
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/bin/config.ts
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/lib/sep-stack.ts
  packages/aws-rfdk/docs/diagrams/deadline/ConfigureSpotEventPlugin.svg
  packages/aws-rfdk/docs/diagrams/deadline/SpotEventPluginFleet.svg
  packages/aws-rfdk/docs/upgrade/index.md
  packages/aws-rfdk/docs/upgrade/upgrading-0.39.md
  packages/aws-rfdk/lib/deadline/lib/configure-spot-event-plugin.ts
  packages/aws-rfdk/lib/deadline/lib/spot-event-plugin-fleet.ts
  packages/aws-rfdk/lib/deadline/test/configure-spot-event-plugin.test.ts
  packages/aws-rfdk/lib/deadline/test/spot-event-plugin-fleet.test.ts
  packages/aws-rfdk/lib/lambdas/nodejs/configure-spot-event-plugin/conversion.ts
  packages/aws-rfdk/lib/lambdas/nodejs/configure-spot-event-plugin/test/conversion.test.ts
  packages/aws-rfdk/lib/lambdas/nodejs/configure-spot-event-plugin/test/handler.test.ts
  packages/aws-rfdk/lib/lambdas/nodejs/configure-spot-event-plugin/types.ts
  packages/aws-rfdk/lib/lambdas/nodejs/lib/configure-spot-event-plugin/test/spot-event-plugin-client.test.ts
Labels: contribution/core
