Repository aws/aws-rfdk, pull requests merged in 2021-06, with the labels that each got.

#458 chore(merge-back): 0.33.0
  CHANGELOG.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/package.json
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/package.json
  examples/deadline/EC2-Image-Builder/python/setup.py
  examples/deadline/EC2-Image-Builder/ts/package.json
  integ/package.json
  lambda-layers/package.json
  lerna.json
  package.json
  packages/aws-rfdk/package.json
  tools/cdk-build-tools/package.json
  tools/pkglint/package.json
Labels: pr/no-squash

#301 feat(deadline): add ability to horizontally scale the RenderQueue
  packages/aws-rfdk/lib/deadline/lib/render-queue-ref.ts
  packages/aws-rfdk/lib/deadline/lib/render-queue.ts
  packages/aws-rfdk/lib/deadline/test/render-queue.test.ts
Labels: contribution/core

#446 chore(lambdas): add retry logic to ACM certificate importer
  packages/aws-rfdk/lib/lambdas/nodejs/lib/backoff-generator/backoff-generator.ts
  packages/aws-rfdk/lib/lambdas/nodejs/lib/backoff-generator/index.ts
  packages/aws-rfdk/lib/lambdas/nodejs/lib/backoff-generator/test/backoff-generator.test.ts
  packages/aws-rfdk/lib/lambdas/nodejs/x509-certificate/acm-handlers.ts
  packages/aws-rfdk/lib/lambdas/nodejs/x509-certificate/test/acm-handlers.test.ts
Labels: contribution/core

#469 chore(deps): bumping cdk from 1.106.1 to 1.108.1
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/package.json
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/package.json
  examples/deadline/EC2-Image-Builder/python/setup.py
  examples/deadline/EC2-Image-Builder/ts/package.json
  integ/package.json
  lambda-layers/package.json
  package.json
  packages/aws-rfdk/package.json
  tools/cdk-build-tools/package.json
  tools/pkglint/package.json
  yarn.lock
Labels: contribution/core

#472 chore(release): 0.34.0
  CHANGELOG.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/package.json
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/package.json
  examples/deadline/EC2-Image-Builder/python/setup.py
  examples/deadline/EC2-Image-Builder/ts/package.json
  integ/package.json
  lambda-layers/package.json
  lambda-layers/yarn.lock
  lerna.json
  package.json
  packages/aws-rfdk/lib/deadline/lib/render-queue-ref.ts
  packages/aws-rfdk/lib/deadline/lib/render-queue.ts
  packages/aws-rfdk/lib/deadline/test/render-queue.test.ts
  packages/aws-rfdk/lib/lambdas/nodejs/lib/backoff-generator/backoff-generator.ts
  packages/aws-rfdk/lib/lambdas/nodejs/lib/backoff-generator/index.ts
  packages/aws-rfdk/lib/lambdas/nodejs/lib/backoff-generator/test/backoff-generator.test.ts
  packages/aws-rfdk/lib/lambdas/nodejs/x509-certificate/acm-handlers.ts
  packages/aws-rfdk/lib/lambdas/nodejs/x509-certificate/test/acm-handlers.test.ts
  packages/aws-rfdk/package.json
  tools/cdk-build-tools/package.json
  tools/pkglint/package.json
  yarn.lock
Labels: pr/no-squash

#473 chore(merge-back): 0.34.0
  CHANGELOG.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/package.json
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/package.json
  examples/deadline/EC2-Image-Builder/python/setup.py
  examples/deadline/EC2-Image-Builder/ts/package.json
  integ/package.json
  lambda-layers/package.json
  lambda-layers/yarn.lock
  lerna.json
  package.json
  packages/aws-rfdk/package.json
  tools/cdk-build-tools/package.json
  tools/pkglint/package.json
Labels: pr/no-squash

#464 fix(core): increase timeout for AcmCertificateImporter
  packages/aws-rfdk/lib/core/lib/imported-acm-certificate.ts
  packages/aws-rfdk/lib/lambdas/nodejs/x509-certificate/acm-handlers.ts
Labels: contribution/core

#476 fix(core): increase lambda timeout for X509Certificate* constructs
  packages/aws-rfdk/lib/core/lib/x509-certificate.ts
Labels: contribution/core

#480 chore(release): 0.35.0
  CHANGELOG.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/package.json
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/package.json
  examples/deadline/EC2-Image-Builder/python/setup.py
  examples/deadline/EC2-Image-Builder/ts/package.json
  integ/package.json
  lambda-layers/package.json
  lerna.json
  package.json
  packages/aws-rfdk/lib/core/lib/imported-acm-certificate.ts
  packages/aws-rfdk/lib/core/lib/x509-certificate.ts
  packages/aws-rfdk/lib/lambdas/nodejs/x509-certificate/acm-handlers.ts
  packages/aws-rfdk/package.json
  tools/cdk-build-tools/package.json
  tools/pkglint/package.json
Labels: pr/no-squash

#482 chore(merge-back): 0.35.0
  CHANGELOG.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/package.json
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/package.json
  examples/deadline/EC2-Image-Builder/python/setup.py
  examples/deadline/EC2-Image-Builder/ts/package.json
  integ/package.json
  lambda-layers/package.json
  lerna.json
  package.json
  packages/aws-rfdk/package.json
  tools/cdk-build-tools/package.json
  tools/pkglint/package.json
Labels: pr/no-squash

#477 chore(deps): add resolution for diff and remove nodeunit
  package.json
  tools/cdk-build-tools/bin/cdk-test.ts
  tools/cdk-build-tools/lib/package-info.ts
  tools/cdk-build-tools/package.json
  yarn.lock
Labels: contribution/core, dependencies

#479 chore(deps): add resolutions for normalize-url and parse-url
  package.json
  yarn.lock
Labels: contribution/core, dependencies

#478 chore(deps): add resolutions for trim-newlines and meow
  package.json
  yarn.lock
Labels: contribution/core, dependencies

#484 chore(deps): use jsii/superchain:node14 for rfdk development
  scripts/rfdk_build_environment.sh
Labels: contribution/core, dependencies

#314 feat(examples): local zones examples
  examples/deadline/Local-Zone/README.md
  examples/deadline/Local-Zone/python/.gitignore
  examples/deadline/Local-Zone/python/README.md
  examples/deadline/Local-Zone/python/cdk.json
  examples/deadline/Local-Zone/python/package/__init__.py
  examples/deadline/Local-Zone/python/package/app.py
  examples/deadline/Local-Zone/python/package/lib/__init__.py
  examples/deadline/Local-Zone/python/package/lib/compute_tier.py
  examples/deadline/Local-Zone/python/package/lib/config.py
  examples/deadline/Local-Zone/python/package/lib/network_tier.py
  examples/deadline/Local-Zone/python/package/lib/security_tier.py
  examples/deadline/Local-Zone/python/package/lib/service_tier.py
  examples/deadline/Local-Zone/python/requirements.txt
  examples/deadline/Local-Zone/python/setup.py
  examples/deadline/Local-Zone/python/source.bat
  examples/deadline/Local-Zone/ts/.gitignore
  examples/deadline/Local-Zone/ts/.npmignore
  examples/deadline/Local-Zone/ts/README.md
  examples/deadline/Local-Zone/ts/bin/app.ts
  examples/deadline/Local-Zone/ts/bin/config.ts
  examples/deadline/Local-Zone/ts/cdk.json
  examples/deadline/Local-Zone/ts/clean.sh
  examples/deadline/Local-Zone/ts/lib/compute-tier.ts
  examples/deadline/Local-Zone/ts/lib/network-tier.ts
  examples/deadline/Local-Zone/ts/lib/security-tier.ts
  examples/deadline/Local-Zone/ts/lib/service-tier.ts
  examples/deadline/Local-Zone/ts/package.json
  examples/deadline/Local-Zone/ts/tsconfig.json
  scripts/rfdk_build_environment.sh
Labels: contribution/core

#465 fix(core): Convert group & pool names in SpotEventPluginFleet to lowercase
  packages/aws-rfdk/lib/deadline/lib/configure-spot-event-plugin.ts
  packages/aws-rfdk/lib/deadline/lib/spot-event-plugin-fleet.ts
  packages/aws-rfdk/lib/deadline/test/spot-event-plugin-fleet.test.ts
Labels: contribution/core
