Repository aws/aws-rfdk, pull requests merged in 2021-09, with the labels that each got.

#557 fix(integ): add special case in repository tests for deadline 10.1.18.5
  integ/components/deadline/deadline_01_repository/test/deadline_01_repository.test.ts
Labels: contribution/core

#559 chore: Merge branch 'mainline' into merge_mainline_feature_sm
  integ/components/deadline/common/scripts/bastion/utils/configure-deadline.sh
  integ/components/deadline/deadline_01_repository/test/deadline_01_repository.test.ts
  package.json
  packages/aws-rfdk/lib/deadline/scripts/bash/installDeadlineRepository.sh
  packages/aws-rfdk/lib/deadline/scripts/python/client-rq-connection.py
  packages/aws-rfdk/lib/deadline/test/asset-constants.ts
  yarn.lock
Labels: pr/no-squash

#569 chore(deps): remove resolutions for parse-url and normalize-url
  package.json
  yarn.lock
Labels: dependencies, contribution/core

#562 feat(examples): add deadline secrets management options to basic example
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/README.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/app.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/config.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/lib/service_tier.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/README.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/bin/app.ts
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/bin/config.ts
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/lib/service-tier.ts
Labels: contribution/core

#553 feat(integ): add Deadline secrets management integration tests
  integ/components/deadline/common/jest-matchers.ts
  integ/components/deadline/deadline_05_secretsManagement/bin/deadline_05_secretsManagement.ts
  integ/components/deadline/deadline_05_secretsManagement/cdk.json
  integ/components/deadline/deadline_05_secretsManagement/lib/secretsManagement-testing-tier.ts
  integ/components/deadline/deadline_05_secretsManagement/scripts/bastion/testing/SM-run-secrets-command.sh
  integ/components/deadline/deadline_05_secretsManagement/test/deadline_05_secretsManagement.test.ts
  integ/jest.config.js
  integ/lib/render-struct.ts
  integ/lib/storage-struct.ts
  integ/lib/testing-tier.ts
  integ/lib/thinkbox-docker-image-overrides.ts
  integ/scripts/bash/deploy-all.sh
  integ/test-config.sh
Labels: contribution/core

#570 chore(deps): add resolution for set-value and update resolution for pac-resolver
  package.json
  yarn.lock
Labels: dependencies, contribution/core

#578 chore: Revert "Modified basic example to make a secrets management PoC"
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/.gitignore
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/bin/app.ts
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/bin/config.ts
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/lib/compute-tier.ts
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/lib/network-tier.ts
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/lib/service-tier.ts
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/lib/ssm-policy-aspect.ts
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/lib/workstation-tier.ts
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/scripts/bash/installDeadlineClient.sh
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/scripts/powershell/installDeadlineClient.ps1
  packages/aws-rfdk/lib/deadline/lib/repository.ts
  packages/aws-rfdk/lib/deadline/scripts/bash/installDeadlineRepository.sh
Labels: contribution/core

#558 chore(deadline): add secrets management documentation
  packages/aws-rfdk/docs/upgrade/index.md
  packages/aws-rfdk/docs/upgrade/upgrading-0.38.md
  packages/aws-rfdk/lib/deadline/README.md
  packages/aws-rfdk/lib/deadline/lib/render-queue-ref.ts
Labels: documentation, contribution/core
