Repository aws/aws-rfdk, pull requests merged in 2023-12, with the labels that each got.

#1154 chore(deps): bump CDK to 2.114.1
  .github/dependabot.yml
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/package/config.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/bin/config.ts
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/package.json
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/package/config.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/bin/config.ts
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/package.json
  examples/deadline/EC2-Image-Builder/python/setup.py
  examples/deadline/EC2-Image-Builder/ts/package.json
  examples/deadline/Local-Zone/python/package/lib/config.py
  examples/deadline/Local-Zone/python/setup.py
  examples/deadline/Local-Zone/ts/bin/config.ts
  examples/deadline/Local-Zone/ts/package.json
  integ/package.json
  lambda-layers/package.json
  package.json
  packages/aws-rfdk/lib/core/lib/deployment-instance.ts
  packages/aws-rfdk/lib/core/lib/health-monitor.ts
  packages/aws-rfdk/lib/core/lib/mongodb-instance.ts
  packages/aws-rfdk/lib/core/lib/staticip-server.ts
  packages/aws-rfdk/lib/core/test/deployment-instance.test.ts
  packages/aws-rfdk/lib/core/test/exporting-log-group.test.ts
  packages/aws-rfdk/lib/core/test/log-group-factory.test.ts
  packages/aws-rfdk/lib/core/test/mongodb-installer.test.ts
  packages/aws-rfdk/lib/core/test/mountable-ebs.test.ts
  packages/aws-rfdk/lib/core/test/mountable-efs.test.ts
  packages/aws-rfdk/lib/core/test/mountable-fsx-lustre.test.ts
  packages/aws-rfdk/lib/core/test/staticip-server.test.ts
  packages/aws-rfdk/lib/deadline/test/database-connection.test.ts
  packages/aws-rfdk/lib/deadline/test/render-queue.test.ts
  packages/aws-rfdk/lib/deadline/test/repository.test.ts
  packages/aws-rfdk/lib/deadline/test/worker-configuration.test.ts
  packages/aws-rfdk/lib/lambdas/nodejs/asg-attach-eni/test/test.ts
  packages/aws-rfdk/lib/lambdas/nodejs/lib/backoff-generator/test/backoff-generator.test.ts
  packages/aws-rfdk/lib/lambdas/nodejs/unhealthyFleetAction/test/unhealthyFleetAction.test.ts
  packages/aws-rfdk/package.json
  scripts/fix-peer-deps.sh
  scripts/rfdk_build_environment.sh
  yarn.lock
Labels: dependencies

#1162 chore: update build command to use yarn
  CONTRIBUTING.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/README.md
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/README.md
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/README.md
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/README.md
  examples/deadline/EC2-Image-Builder/python/README.md
  examples/deadline/EC2-Image-Builder/ts/README.md
  examples/deadline/Local-Zone/python/README.md
  examples/deadline/Local-Zone/ts/README.md
  integ/README.md
  scripts/prep_release.sh
Labels: contribution/core

#1163 chore(deps): deprecate NodeJS pre 18.*
  README.md
  integ/package.json
  lambda-layers/package.json
  packages/aws-rfdk/docs/upgrade/upgrading-1.3.md
  packages/aws-rfdk/lib/index.ts
  packages/aws-rfdk/package.json
  tools/pkglint/lib/rules.ts
Labels: dependencies, contribution/core

#1173 chore(merge-back): 1.3.0
  CHANGELOG.md
  bump.sh
  examples/deadline/All-In-AWS-Infrastructure-Basic/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-Basic/ts/package.json
  examples/deadline/All-In-AWS-Infrastructure-SEP/python/setup.py
  examples/deadline/All-In-AWS-Infrastructure-SEP/ts/package.json
  examples/deadline/EC2-Image-Builder/python/setup.py
  examples/deadline/EC2-Image-Builder/ts/package.json
  examples/deadline/Local-Zone/python/setup.py
  examples/deadline/Local-Zone/ts/package.json
  integ/package.json
  lambda-layers/yarn.lock
  lerna.json
  package.json
  packages/aws-rfdk/package.json
  tools/pkglint/package.json
Labels: pr/no-squash
